bkash/urls.py
"""
Author: Raju Ahmed Shetu
"""
from django.urls import path
from . import views
app_name='bkash'
urlpatterns = [
    path('payment/create', views.PaymentCreateApiView.as_view(), name='payment_create_api_view'),
    path('payment/execute', views.PaymentExecuteApiView.as_view(), name='payment_execute_api_view'),
]

# 127.0.0.1:8000/bkash/payment/create
# 127.0.0.1:8000/bkash/payment/execute

bkash/models.py
from django.db import models
from .managers import PaymentManager, TransactionManger
# Create your models here.
'''
{
    "paymentID": "13HYFS31539088469895",
    "createTime": "2018-10-09T12:34:29:962 GMT+0000",
    "orgLogo": "https://s3-ap-southeast-1.amazonaws.com/merchantlogo.sandbox.bka.sh/merchant-default-logo.png",
    "orgName": "TestDemoMerchant",
    "transactionStatus": "Initiated",
    "amount": "100",
    "currency": "BDT",
    "intent": "sale",
    "merchantInvoiceNumber": "od8ZBmQx4nA"
}
'''
from django.conf import settings
from model_utils.models import TimeStampedModel, SoftDeletableModel, SoftDeletableManager
AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL')


class Payment(TimeStampedModel, SoftDeletableModel):
    paymentID = models.CharField(max_length=50, unique=True, editable=False, primary_key=True)
    user = models.ForeignKey(
        AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='payments'
    )
    createTime = models.TextField()
    orgLogo = models.URLField(max_length=250)
    orgName = models.CharField(max_length=100)
    transactionStatus = models.CharField(max_length=50)
    amount = models.CharField(max_length=50)
    currency = models.CharField(max_length=20)
    intent = models.CharField(max_length=20)
    merchantInvoiceNumber = models.CharField(max_length=30)

    objects = PaymentManager()
    soft_manager = SoftDeletableManager()

    class Meta:
        db_table = 'payments'
        ordering = ('-created', )




'''
{
    'paymentID': 'OFN3R7S1539093934542',
    'createTime': '2018-10-09T14:05:34:643 GMT+0000',
    'updateTime': '2018-10-09T14:06:20:600 GMT+0000',
    'trxID': '5J93015CSH',
    'transactionStatus': 'Completed',
    'amount': '17.29',
    'currency': 'BDT',
    'intent': 'sale',
    'merchantInvoiceNumber': 'WqDJJMDxVMa'
}
'''


class Transaction(TimeStampedModel, SoftDeletableModel):
    paymentID = models.CharField(max_length=50)
    createTime = models.TextField()
    updateTime = models.TextField()
    trxID = models.CharField(max_length=50, primary_key=True, editable=False, unique=True)
    transactionStatus = models.CharField(max_length=20)
    amount = models.CharField(max_length=20)
    currency = models.CharField(max_length=20)
    intent = models.CharField(max_length=20)
    merchantInvoiceNumber = models.CharField(max_length=30)
    user = models.ForeignKey(
        AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='transactions'
    )

    objects = TransactionManger()
    soft_manager = SoftDeletableManager()

    class Meta:
        db_table = 'transactions'
        ordering = ('-created', )

bkash/views.py
# Create your views here.
import requests

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from . import utils as bkash_utils
from .models import Payment, Transaction


# from django.views.decorators.csrf import csrf_exempt

class PaymentCreateApiView(APIView):
    # @csrf_exempt
    def post(self, request):
        try:
            auth_body, auth_headers = bkash_utils.get_header_body_for_token_auth()
            # print(auth_body)
            # print(auth_headers)
            auth_response = requests.post(
                bkash_utils.get_bkash_app_payment_token_grant_url(),
                json=auth_body,
                headers=auth_headers
            )
            
            response = requests.post(
                bkash_utils.get_bkash_app_payment_create_url(),
                json=dict(request.data, **dict(currency='BDT', merchantInvoiceNumber=bkash_utils.generate_unique_id())),
                headers=bkash_utils.get_header_for_payment_create(auth_response.json().get('id_token'))
            )
            
            if response.status_code == 200 and response.json() and 'paymentID' in response.json():
                try:
                    payment = Payment(user=request.user, **response.json())
                    # print(payment)
                    payment.save()
                except Exception as exc:
                    print(exc)
            # print(response.json())
            return Response(response.json(), status=status.HTTP_200_OK)
        except Exception as exc:
            return Response(dict(
                status=500,
                message=exc.args[0]
            ), status=status.HTTP_500_INTERNAL_SERVER_ERROR)



class PaymentExecuteApiView(APIView):
    # @csrf_exempt
    def post(self, request):
        try:
            if 'paymentID' not in request.data:
                return Response(
                    dict(
                        status=500,
                        message='PaymentID is required'
                    ),
                    status=status.HTTP_500_INTERNAL_SERVER_ERROR
                )
            auth_body, auth_headers = bkash_utils.get_header_body_for_token_auth()
            auth_response = requests.post(
                bkash_utils.get_bkash_app_payment_token_grant_url(),
                json=auth_body,
                headers=auth_headers
            )
            response = requests.post(
                '%s/%s'%(bkash_utils.get_bkash_app_payment_execute_url(), request.data.get('paymentID')),
                headers=bkash_utils.get_header_for_payment_create(auth_response.json().get('id_token'))
            )
            if response.status_code == 200 and response.json() and ('paymentID' in response.json() and 'trxID' in response.json()):
                try:
                    transaction = Transaction(user=request.user, **response.json())
                    transaction.save()
                except Exception as exc:
                    print(exc)

            return Response(response.json(), status=status.HTTP_200_OK)
        except Exception as exc:
            return Response(dict(
                status=500,
                message=exc.args[0]
            ), status=status.HTTP_500_INTERNAL_SERVER_ERROR)

templates/bkash_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script> 
    <script src="https://scripts.sandbox.bka.sh/versions/1.2.0-beta/checkout/bKash-checkout-sandbox.js"></script> 
    
    <title>bkash payment</title>
</head>
<body>
    <h1>
        <p> amount: '100.50' </p> 
        
        <p>intent: 'sale'</p>
    </h1>

    <button id="bKash_button">Pay with bKash</button>
    <script>
        var paymentID = ''; 
        bKash.init({ 
        paymentMode: 'checkout', //fixed value ‘checkout’ 
        //paymentRequest format: {amount: AMOUNT, intent: INTENT} 
        //intent options 
        //1) ‘sale’ – immediate transaction (2 API calls) 
        //2) ‘authorization’ – deferred transaction (3 API calls) 
        paymentRequest: { 
            amount: '100.50', //max two decimal points allowed 
            intent: 'sale' 
        }, 
        createRequest: function(request) { //request object is basically the paymentRequest object, automatically pushed by the script in createRequest method 
            $.ajax({ 
            url: '{% url "bkash:payment_create_api_view" %}',
            type: 'POST', 
            contentType: 'application/json',  
            success: function(data) { 
                data = JSON.parse(data);
                if (data && data.paymentID != null) { 
                paymentID = data.paymentID; 
                bKash.create().onSuccess(data); //pass the whole response data in bKash.create().onSucess() method as a parameter 
                } else { 
                bKash.create().onError(); 
                } 
            }, 
            error: function() { 
                bKash.create().onError(); 
            } 
            }); 
        },
        executeRequestOnAuthorization: function() { 
            $.ajax({ 
            url: '{% url "bkash:payment_execute_api_view" %}',
            type: 'POST', 
            contentType: 'application/json', 
            data: JSON.stringify({ 
                "paymentID": paymentID 
            }), 
            success: function(data) { 
                data = JSON.parse(data);
                if (data && data.paymentID != null) { 
                window.location.href = '{% url "demo_api:demo_success" %}';//Merchant’s success page 
                } else { 
                bKash.execute().onError(); 
                } 
            }, 
            error: function() { 
                bKash.execute().onError(); 
            } 
            }); 
        } 
        });
    </script>
</body>
</html>